name: Ledger CI
# triggers the CI pipeline on new commits or pull requests
on: [push, pull_request]
jobs:
  build-and-test:
    # provides an ephemeral Ubuntu VM
    runs-on: ubuntu-latest
    steps:
      # clones the code into the VM workspace
      - uses: actions/checkout@v4
      # installs the Go compiler with the correct version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.0'
      # performs static analysis and fails the build on violations
      # - name: golangci-lint
        # uses: golangci/golangci-lint-action@v3
        # with:
          # version: latest
      # executes the test suite and injects sensors to catch data-races
      - name: Run Tests with Race Detector
        run: go test -v -race ./...